import React, { useState } from 'react';
import { 
  Download, 
  Copy, 
  Check, 
  FileText, 
  FileSpreadsheet, 
  Share2 
} from 'lucide-react';
import { Modal } from '../ui/Modal';
import { useToast } from '../../context/ToastContext';

export function ExportDialog({
  isOpen,
  onClose,
  items = [],
  sessionMeta = null,
}) {
  const { addToast } = useToast();
  const [copied, setCopied] = useState(false);

  const projectName = sessionMeta?.idea || 'Naming Studio Exploration';
  const timestamp = new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

  // Generate polished text document
  const generateTextContent = () => {
    let output = `====================================================\n`;
    output += `           NOVA — AI NAME STUDIO SHORTLIST          \n`;
    output += `====================================================\n\n`;
    output += `Project: ${projectName}\n`;
    output += `Generated: ${timestamp}\n`;
    output += `Total Shortlisted: ${items.length} candidates\n`;
    output += `Legal Note: Scores and similarity indicators are AI creative guidance, not trademark clearance.\n\n`;
    output += `----------------------------------------------------\n\n`;

    items.forEach((item, index) => {
      output += `[${index + 1}] ${item.name.toUpperCase()}\n`;
      output += `Overall Score: ${item.score}/100\n`;
      output += `Style: ${item.style || 'Modern'}\n`;
      output += `Pronunciation: ${item.pronunciation || item.name} (${item.ipa || ''})\n`;
      output += `Collision Advisory: ${item.collisionLevel || 'Low'}\n`;
      output += `Why It Works:\n`;
      output += `  • Meaning: ${item.meaning || item.explanation}\n`;
      output += `  • Sound: ${item.sound || 'Clean acoustic balance'}\n`;
      output += `  • Emotion: ${item.emotion || 'Modern confidence'}\n`;
      output += `Metrics:\n`;
      output += `  • Memorability: ${item.metrics?.memorability || 90}/100\n`;
      output += `  • Brandability: ${item.metrics?.brandability || 90}/100\n`;
      output += `  • Pronunciation: ${item.metrics?.pronunciation || 90}/100\n`;
      output += `  • Distinctiveness: ${item.metrics?.distinctiveness || 90}/100\n`;
      output += `  • Emotional Fit: ${item.metrics?.emotionalFit || 90}/100\n\n`;
      output += `----------------------------------------------------\n\n`;
    });

    output += `Generated by NOVA — Turn ideas into names people remember.\n`;
    return output;
  };

  // Generate CSV content
  const generateCSVContent = () => {
    const headers = ['Name', 'Score', 'Style', 'Pronunciation', 'Collision_Level', 'Meaning', 'Memorability', 'Brandability', 'Pronunciation_Metric', 'Distinctiveness', 'Emotional_Fit'];
    const rows = items.map((i) => [
      `"${i.name}"`,
      i.score,
      `"${i.style || 'Modern'}"`,
      `"${i.pronunciation || i.name}"`,
      `"${i.collisionLevel || 'Low'}"`,
      `"${(i.meaning || i.explanation || '').replace(/"/g, '""')}"`,
      i.metrics?.memorability || 90,
      i.metrics?.brandability || 90,
      i.metrics?.pronunciation || 90,
      i.metrics?.distinctiveness || 90,
      i.metrics?.emotionalFit || 90,
    ]);

    return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  };

  const handleCopyClipboard = () => {
    const text = generateTextContent();
    navigator.clipboard.writeText(text);
    setCopied(true);
    addToast({
      type: 'success',
      title: 'Copied to Clipboard',
      message: 'Full formatted shortlist copied.'
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTXT = () => {
    const text = generateTextContent();
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `nova-shortlist-${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
    addToast({
      type: 'success',
      title: 'TXT Downloaded',
      message: 'Shortlist saved to your device.'
    });
  };

  const handleDownloadCSV = () => {
    const csv = generateCSVContent();
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `nova-shortlist-${Date.now()}.csv`;
    link.click();
    URL.revokeObjectURL(url);
    addToast({
      type: 'success',
      title: 'CSV Downloaded',
      message: 'Spreadsheet saved to your device.'
    });
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Export Naming Shortlist"
      subtitle={`Export ${items.length} shortlisted candidates with complete metrics, phonetics, and creative rationales.`}
      maxWidth="max-w-2xl"
    >
      <div className="space-y-5">
        {/* Export Options */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <button
            type="button"
            onClick={handleCopyClipboard}
            className="p-4 rounded-xl bg-[#090C16] border border-white/10 hover:border-purple-500/40 hover:bg-purple-950/20 text-left transition-all group"
          >
            <div className="p-2 rounded-lg bg-purple-500/10 text-purple-400 w-fit mb-3 group-hover:scale-110 transition-transform">
              {copied ? <Check className="w-5 h-5 text-emerald-400" /> : <Copy className="w-5 h-5" />}
            </div>
            <h4 className="text-xs font-bold text-white tracking-tight">
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </h4>
            <p className="text-[11px] text-slate-400 mt-1">Formatted summary for Slack, Docs, or email.</p>
          </button>

          <button
            type="button"
            onClick={handleDownloadTXT}
            className="p-4 rounded-xl bg-[#090C16] border border-white/10 hover:border-cyan-500/40 hover:bg-cyan-950/20 text-left transition-all group"
          >
            <div className="p-2 rounded-lg bg-cyan-500/10 text-cyan-400 w-fit mb-3 group-hover:scale-110 transition-transform">
              <FileText className="w-5 h-5" />
            </div>
            <h4 className="text-xs font-bold text-white tracking-tight">
              Download TXT
            </h4>
            <p className="text-[11px] text-slate-400 mt-1">Universal plain text brand docket.</p>
          </button>

          <button
            type="button"
            onClick={handleDownloadCSV}
            className="p-4 rounded-xl bg-[#090C16] border border-white/10 hover:border-emerald-500/40 hover:bg-emerald-950/20 text-left transition-all group"
          >
            <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 w-fit mb-3 group-hover:scale-110 transition-transform">
              <FileSpreadsheet className="w-5 h-5" />
            </div>
            <h4 className="text-xs font-bold text-white tracking-tight">
              Download CSV
            </h4>
            <p className="text-[11px] text-slate-400 mt-1">Structured data for Excel or Google Sheets.</p>
          </button>
        </div>

        {/* Text Preview Box */}
        <div>
          <label className="text-xs font-bold uppercase tracking-wider text-slate-400 block mb-1.5">
            Export Preview
          </label>
          <pre className="p-4 rounded-xl bg-[#070912] border border-white/10 font-mono text-[11px] text-slate-300 max-h-[220px] overflow-y-auto whitespace-pre-wrap leading-relaxed select-all">
            {generateTextContent()}
          </pre>
        </div>
      </div>
    </Modal>
  );
}
